### ISSUE TITLE
availability of location information is interrupted when rotating the device

### ISSUE THREAD

**Issue by wuan** [wuan/bo-android#129]
We could have a short lived cache to keep location information while rotating the device. Sometimes it takes several seconds until the location is fixed after rotation.

**Comment by d3xter** [comment]
This is already fixed on the 1.6 branch. The problem is, that when rotating the screen, the LocationHandler sends out a NULL-Location to all clients.

When Main reattaches to Location-Updates it receives the last NULL location.
