### ISSUE TITLE
Timer sometimes starts higher than 60 seconds

### ISSUE THREAD

**Issue by Ergonomicmike** [wuan/bo-android#130]
Sorry if this has been reported before. (Don't see an easy way to search issues in the github.)

Version 1.5.4 (175). 

Sometimes the 60 second timer starts higher than 60 seconds. (See screen shot.) It doesn't always happen. Seems to happen when a strike comes in and restarts the timer? I never noticed it happening with older version 1.3.7.

![more than 60](https://cloud.githubusercontent.com/assets/15025888/15120924/ec3e1cee-15cc-11e6-9868-28facd2b5b8c.jpg)

**Comment by wuan** [comment]
The request timestamp from the server is used for timing. If the time on your phone is not synced, there may be offsets.

We should not use server times for internal period calculations.
