### ISSUE TITLE
15 Minute Historic TimeStep not working?

### ISSUE THREAD

**Issue by Ergonomicmike** [wuan/bo-android#135]
Not a big deal (could always eliminate the 15 minute option if an issue), but here's a 1 minute video showing that the 15 minute historic time step isn't working. (v1.5.7.)

https://vid.me/AynX

**Comment by wuan** [comment]
Thanks for reporting, it seems that the preference change is not recognized. We will have a look at that.

**Comment by wuan** [comment]
This was just an error while calculating the shown time. The data was already correct.
