### ISSUE TITLE
Lightning-Count doesn't match Raster vs Strikes

### ISSUE THREAD

**Issue by d3xter** [wuan/bo-android#162]
The lightning-count is different whether the RasterShape is shown vs the StrikeShape.

Is this how it should work?

**Comment by wuan** [comment]
The strikes are show worldwide while the source of the raster data is the whilte rectangle. In addition there is the count threshold parameter which even more reduces the strike count in the raster case.
The strike counts do usually differ between the two modes.

**Comment by d3xter** [comment]
Oh you are right. My bad ^^
