### ISSUE TITLE
App does not work since today (25.5.)

### ISSUE THREAD

**Issue by tmstaedt** [wuan/bo-android#174]
Yesterday everything was okay. I didn't change anything.

**Comment by tmstaedt** [comment]
Now works again

**Comment by wuan** [comment]
The blitzrortung.org data server ran out of disk space. This started around 05:30 UTC and was fixed around 12:40 UTC on May 25th. Sorry for the incovenience.
In the metrics you can see the import spike around 12:40 UTC reading all the so far missing data: https://raijin.tryb.de/d/000000005/bo-webservice?orgId=1&from=1527224400000&to=1527254100000
