### ISSUE TITLE
Inclusion at f-droid.org

### ISSUE THREAD

**Issue by sm4rk0** [wuan/bo-android#178]
Hi. I like your application very much.
Do you agree with including it on [f-droid.org](https://f-droid.org/en/about/)?
It would bring it to more users and support the FOSS idea.

Cheers,
Marko

**Comment by wuan** [comment]
Hi Marko,

we tried this some years ago. It did not work our because of the Google Map V1 API dependency. We have to get rid of this before this app can be included in f-droid.org.
See https://gitlab.com/fdroid/fdroiddata/merge_requests/1137

**Comment by wuan** [comment]
Work on OSM integration was already started, but it is still in very early stage.

**Comment by wuan** [comment]
Using OSM Mapview in 2.0 Beta works quite well now. Started another try to enter F-Droid: https://gitlab.com/fdroid/fdroiddata/merge_requests/4388

**Comment by wuan** [comment]
Thanks for reporting this, the tag is pushed now.
