### ISSUE TITLE
Not working on old Nook HD+ with CM10

### ISSUE THREAD

**Issue by Ergonomicmike** [wuan/bo-android#179]
Ever since version 1.4, (I think it was) Blitzortung stopped working on my Nook HD+ with custom ROM. (KitKat.)

If my hardware is too old, I will understand.

![blitzortung has stopped](https://user-images.githubusercontent.com/15025888/43020641-3626a3c0-8c50-11e8-82b8-89368ee49282.jpg)

**Comment by wuan** [comment]
The app is running on CM7. A too old OS should not be the problem here. Can you try to get log output of the app crashing?

**Comment by Ergonomicmike** [comment]
Log output: Would that be a logcat thing? Or a tombstone? Or? (Need some hand holding to get you what you need.) Tnx.

**Comment by Ergonomicmike** [comment]
@wuan , here's a log cat. I run CM 10.1 on my HD+.

[blitzortung.crash.txt](https://github.com/wuan/bo-android/files/2239731/blitzortung.crash.txt)

Please let me know if you need more.

**Comment by sm4rk0** [comment]
This device doesn't have a GPS receiver. [Source](https://nook.barnesandnoble.com/u/Support-nook-hd-plus/379003760):

> Do Android Apps work with Google location services?
> Rather than using GPS, you can let some Google apps use Wi-Fi® data to determine your approximate location. This capability may be useful for local searches and other services. To enable or disable this feature:
> 1. Go to Settings.
> 2. Tap Location Services.
> 3. Tap the checkbox labeled Location & Google search.

**Comment by Ergonomicmike** [comment]
Thanks. It's true that my Nook HD+ doesn't have GPS. But I think it's irrelevant.

First, I use the Manual Entry procedure to enter my location.

Second, earlier versions of Blitzortung worked on my HD+.

Third, this current version works on my other tablet when GPS is disabbled.

Fourth, the failure mode is that Blitzortung won't even start now. Unless it's checking for GPS - which, as above, isn't necessary for it to work - and FC's after that, then it must be a problem somewhere else.

**Comment by wuan** [comment]
Yes, that comes from the application. Maybe it helps to ignore these errors and show a toast message instead. Will have a closer look there.

**Comment by wuan** [comment]
@Ergonomicmike, you have enabled manual location and the error still occurs?

**Comment by Ergonomicmike** [comment]
@wuan I can't enable Manual Location in this version because Blitzortung closes before it starts. Presumably, though, Manual Location was still enabled from the last running version. (Until I cleared Data, in an attempt to troubleshoot.)

**Comment by wuan** [comment]
Ok, I will try to ignore this error. Just give me some time, because I'm currently on vacation.

**Comment by Ergonomicmike** [comment]
Danke sehr!

**Comment by wuan** [comment]
Can you try, if the most recent version on the Play store 1.6.6 fixes this?

**Comment by wuan** [comment]
What about the current 2.0.13?

**Comment by wuan** [comment]
Any news here? Does this problem still exist?
