### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by kuba-orlik** [wuan/bo-android#185]
The app crashes on me every time I try to run it. I'll be happy to provide any information you need about my device to help you pin it down

**Comment by wuan** [comment]
Which version do you use. Play store, fdroid? Do you have a version number and a version code?

**Comment by Oswald-Boelcke** [comment]
Same applies here. Immediately FC on the attempt to launch BO.
BO v2.0.2 (222) (F-Droid). All permissions granted, no restrictions applied by XPrivacyLua, no services or broadcast receiver restricted, internet access granted.
Samsung SM-G901F, RR-N-v5.8.5, Magisk v18.1, Xposed
Logcat of time of FC attached. Please advise if further information is required.
[2019-02-09-09-53-21.txt](https://github.com/wuan/bo-android/files/2847658/2019-02-09-09-53-21.txt)
![screenshot_20190209-095236](https://user-images.githubusercontent.com/21972717/52518896-57938b00-2c4a-11e9-93cf-f10de6dd2603.png)

**Comment by wuan** [comment]
Same error like the one reported here https://gitlab.com/fdroid/fdroiddata/issues/1528
```
02-09 09:53:37.656 E/AndroidRuntime(12732): java.lang.NoSuchMethodError: No virtual method setMinZoomLevel(Ljava/lang/Double;)V in class Lorg/blitzortung/android/map/OwnMapView; or its super classes (declaration of 'org.blitzortung.android.map.OwnMapView' appears in /data/app/org.blitzortung.android.app-1/base.apk)
02-09 09:53:37.656 E/AndroidRuntime(12732): 	at org.blitzortung.android.map.OwnMapView.<init>(OwnMapView.kt:52)
```
The only thing which comes to my mind here is, that there could be a problem with the Java 8 support. Will downgrade to Java 7 build and do a release for testing this.

**Comment by Oswald-Boelcke** [comment]
Thanks for the link; interesting. I just discovered BO on F-Droid a few days ago, and affirmative I'd the same issue with v2.0.1, therefore uninstalled but didn't report it (I apologise). Just when v2.0.2 came out I decided to give it another try.
Just for testing purposes, I installed BO v1.6.5 from Google Play Store that I intended not to use. But this version launches without any problem. Going to uninstall it and waiting for a new F-Droid release.
Thanks very much for your work - it's a really interesting project. How about to advertise it on XDA?

**Comment by wuan** [comment]
Can you try the most recent version? The JVM target downgrade seems to have fixed the issue.

**Comment by wuan** [comment]
@Oswald-Boelcke, how would you advertise the availability of the app on XDA?

**Comment by Oswald-Boelcke** [comment]
Hi Andreas. Thanks for the fast job. Excellent. Just downloaded v2.0.3 (223) from F-Droid, and it launched without any problems. Indications of flashes over Europe are available, my present position was recognised. From my point of view, very nice UI but I need to explore the functionalities more within the next days. In case of issues I'll come back here. Guess you can close this report.
********************
Regarding the second question: Unless you're already a member of XDA, register for an account. Afterwards create a thread advertising, offering (or how you would like to call it) Blitzortung - I suggest this forum for the thread: [https://forum.xda-developers.com/android/apps-games](url). Please acknowledge the first sticky thread in the forum.
Here's an example of such a thread by Matthias Urban from Aachen: [https://forum.xda-developers.com/showthread.php?t=1013063](url). He's also on Github ([https://github.com/d4rken](url)) but doesn't publish on F-Droid only via GPS.
If you need any assistance on XDA, don't hesitate to PM me. My XDA user name is also Oswald Boelcke.
