### ISSUE TITLE
Version 2.xx maxzoomlevel=8 is too little.

### ISSUE THREAD

**Issue by Coronarius** [wuan/bo-android#187]
In Version 2.xx maximum zoom level of map is 8. That is much too little for 5 km grid and results in very coarse map without any details. A 5 km grid correlates with 8x8 pixel at zoomlevel 8. I wonder why there is a restriction because version 1.xx has'nt. OSM goes up to 20 or higher (what is much too big on the other hand), but I think it's better to let user decide...

https://wiki.openstreetmap.org/wiki/Zoom_levels

**Comment by wuan** [comment]
The reason for now is the current satellite image basemap which does not exist in higher resolution. We are currently experimenting with dimmed streetmap to overcome this limitation. There will be a change in the map styling hopefully soon.
