### ISSUE TITLE
Improve distinction in naming of map modes

### ISSUE THREAD

**Issue by vubma** [wuan/bo-android#192]
Currently the Map modes are called "Satellite" and "Streetmap". I think it would be better to name them something like "Satellite (Google Maps)" and "Basic (OpenStreetMap)" because it helps distinguish between the map provider. At the very least change "Streetmap" to "OpenStreetMap" to clarify because "Streetmap" could also be interpreted to mean the street view in Google Maps.

**Comment by wuan** [comment]
The map selection is currently work in progress. There is no Google map any more. We will have different parameters in the future.
