### ISSUE TITLE
Feature request: Language change in app 

### ISSUE THREAD

**Issue by JeroenBoersma** [wuan/bo-android#202]
The app now magically chooses the language after installing the app... Sometimes there are good reasons to also manually switch language, for instance if the translation for the OS lacks and the translations for the app are awesome.

Also, it becomes easier to do translations, because you can get context going forth and back between languages.

**Comment by wuan** [comment]
There is a good overview given in https://stackoverflow.com/questions/2900023/change-app-language-programmatically-in-android

Unfortunately there is no official way which seems to be supported. For development you can switch the language of your device globally.

**Comment by JeroenBoersma** [comment]
Thanks for the reply! will do the next time :-)
