### ISSUE TITLE
Zoom and lightenings

### ISSUE THREAD

**Issue by Looping83** [wuan/bo-android#212]
Hi. My scale for cell is set to auto. I can see all the lightenings but some disappear if I zoom in the view. I can see this issue when the "grille" changes from 10 to 5 kms. Is it normal or is it a bug? 
Thanks for help.

**Comment by wuan** [comment]
Which region are you using? There was a problem with the backend raster query for global data, which we fixed yesterday.

Apart from that: do you have a non zero strike count threshold configured? If this is the case, smaller areas can disappear when zooming in.

**Comment by Looping83** [comment]
I'm in France. Ok. 
You can see the problem in these screenshots but I'm not sure it's really a problem. After a zoom+ and a zoom-, it seems that some lights disappear. 
Cheers 
Thierry. 

⁣--------------------------------------------------------------------- 

On y est dans la nasse ! À mardi... 



Télécharger TypeApp pour Android ​

Le 21 juin 2020 à 08:41, à 08:41, "Andreas Würl" <notifications@github.com> a écrit:

**Comment by wuan** [comment]
Hi, 

it seems that the attachments from your email were not uploaded here. Can you add them manually?

Thanks!

**Comment by wuan** [comment]
Closing as we never received more information. Please reopen if the problem still exists.
