### ISSUE TITLE
Add checkbox to disable the toast informing user every n minutes that they're offline

### ISSUE THREAD

**Issue by M-A-R-T-I-N-1** [wuan/bo-android#216]
Whenever I'm offline, blitzortung checking in the background displays this toast: 

"Could not connect.
Please check your network connectivity."

May you please add option to disable that message?

**Comment by Wammez** [comment]
Agree 100%. Very annoying, disturbing anything you are doing every few minutes.  And I KNOW I can not connect because I disabled data transfer myself. 
Otherwise a great app, love it and use it all the time! 
(Did not want to open a new issue post but I will if comments are not getting attention.)

**Comment by wuan** [comment]
We just removed the toasts completely and added logging instead.
