### ISSUE TITLE
App not found in Google Play Store

### ISSUE THREAD

**Issue by Jookus** [wuan/bo-android#223]
I just set up my new smartphone and wondered why my favorite lightning app could not be found in the play store. Is it just a temporary bug or did you remove it from the play store? 😮

Url not working: https://play.google.com/store/apps/details?id=org.blitzortung.android.app

**Comment by frederic34** [comment]
https://github.com/wuan/bo-android/commit/a795932a540362d7bb8f6f2bbba93e52ca36f672

**Comment by wuan** [comment]
Yes, sorry for the inconvenience. The app has been removed by Google as it was not following the prominent disclosure rule when accessing the location in the background. After fixing that it has been restored.
