### ISSUE TITLE
App crashes after setting Background query period

### ISSUE THREAD

**Issue by Aga-C** [wuan/bo-android#235]
Steps to reproduce the crash:
Prerequisites: App has enabled working in the background and disabled battery optimization.
1. Open the app.
2. Go to Preferences.
3. Go to Alarm settings.
4. In Background query period set from off to any time.
5. Go back from Preferences.
6. Go to phone's home screen.
7. Open the app from the background.

Actual result:
App crashes. When I open it again, it crashes again when I try to go to Preferences.
To fix the problem, I have to disable working the app in the background.

App version: 
2.1.8 from F-Droid

Device / OS:
OnePlus 9 Pro / Android 12

Logs:
![image](https://user-images.githubusercontent.com/85929121/161938552-2c4dbe70-148d-4fa1-9419-ecadf1f54f05.png)

Not visible part:
```
java.lang.RuntimeException: Unable to create service org.blitzortung.android.app.AppService: java.lang.IllegalArgumentException: org.blitzortung.android.app: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

**Comment by wuan** [comment]
Thanks for reporting. That problem should be fixed with the current version. Can you give 2.1.9 (282)?

**Comment by wuan** [comment]
We forgot to tag the fixed version. The F-Droid build should be on its way now. Might take a day or two. Sorry for the inconvenience.

**Comment by Aga-C** [comment]
No problem. I have installed this version from Google Play Store some time ago, and it works fine. Thanks.
