### ISSUE TITLE
Zero degrees east grid assignment bug

### ISSUE THREAD

**Issue by AlunHewinson** [wuan/bo-android#253]
When viewing strikes, the first line of grid squares to the east of the 0 meridian appears to always be empty.
My hunch is that they are all being assigned the grid square immediately west of the 0 degree meridian, due to a bug in how the rounding is done, but I don't know where in the code that happens.

Illustration of the issue:
![Screenshot_20240502-094815](https://github.com/wuan/bo-android/assets/3062377/a26caec3-f5b7-4c60-b990-18179f765c58)

**Comment by wuan** [comment]
Thank you for reporting. This has already been fixed in the backend here: https://github.com/wuan/bo-python/pull/29
