### ISSUE TITLE
configureServiceMode called too often

### ISSUE THREAD

**Issue by d3xter** [wuan/bo-android#47]
I looked through the code and noticed that configureServiceMode()
is called upon every run of AppService, even when run in background.
Is it necessary to do that?

Requesting Alarms/Reconfiguring the LocationHandler uses some CPU time every time data is retrieved.

**Comment by wuan** [comment]
Do you mean the call inside the DataEventConsumer in AppService.java?

diff --git a/app/src/main/java/org/blitzortung/android/app/AppService.java b/app/src/main/java/org/blitzortung/android/app/AppService.java
index 4d4aefb..532257e 100644
--- a/app/src/main/java/org/blitzortung/android/app/AppService.java
+++ b/app/src/main/java/org/blitzortung/android/app/AppService.java
@@ -149,7 +149,7 @@ public class AppService extends Service implements Runnable, SharedPreferences.O
             } else if (event instanceof ResultEvent) {
                 ResultEvent resultEvent = (ResultEvent) event;
                 lastParameters = resultEvent.getParameters();
-                configureServiceMode();
+                //configureServiceMode();
             }
 
             releaseWakeLock();

**Comment by d3xter** [comment]
Yes, for example this call to configureServiceMode().

By current data you mean SharedPreferences or retrieved json data?

**Comment by wuan** [comment]
The call is required to update the configuration when changing between historical and realtime mode. Now the call to `alertHandler.reconfigureLocationHandler()` was removed inside `configureServiceMode()` which seems to be not neccessary. It should not be called at every data update.
Thanks for reporting!
