### ISSUE TITLE
LocationProvider inconsistent with Preferences

### ISSUE THREAD

**Issue by d3xter** [wuan/bo-android#81]
At the moment, if you choose a disabled LocationProvider in the preferences,
the preference selection is updated, but in the background the previous provider is used.

The are multiple solutions there:
- Reset the preference when we cannot enable the new provider
- Start a new activity, which lets the user enable GPS/Network
- Disable the options inside the preference view if they provider is not enabled
- Set the provider but dont start it, wait until the LocationProvider is enabled by the user and then start our provider (+ Visual feedback on the map, whether any LocationProvider is running or not)

What is your preferred solution?

**Comment by wuan** [comment]
Thanks for making that clear. I have no strong feelings for a particular solution.

The solution to start a new activity where the user can enable the required provider sounds like the one which should have the best user experience.

**Comment by wuan** [comment]
https://developers.google.com/android/reference/com/google/android/gms/location/SettingsApi#public-methods seems to help solving this problem on newer android versions

**Comment by d3xter** [comment]
That would require to use the google play services.

We could do it this way:
Set the provider but don't "start" it if the provider is disabled.
Meanwhile start the settings activity: http://stackoverflow.com/a/23040461/4706743

As soon as the underlying LocationProvider is enabled, start our provider.
That would solve #82 too.

Let me rewrite the LocationHandler-Part and I'll send you a PR

**Comment by wuan** [comment]
Your contribution is always welcome!

I'm currently working to replace the dependency on the app service in PR #77. This should lead to a better and modular integration of data retrieval. Your feedback there is welcome as well, hopefully ther will be a first stable version in the next weeks.
