### ISSUE TITLE
Disable "Show own location" not working

### ISSUE THREAD

**Issue by d3xter** [wuan/bo-android#84]
When a user disables "Show own location",
inside OwnLocationOverlay the field "item" is set to null, so the users location wont be shown,
but after another LocationEent the "item"-field is set back to a value and the location is shown again

**Comment by d3xter** [comment]
What about setting "visible" inside OwnLocationOverlay?

**Comment by wuan** [comment]
That should fix it for the moment. The *EventConsumers will be obsolete with the switch to RxJava later. OwnLocationOverlay should only subscribe to LocationUpdates when the own location should be shown.
